spring.application.name=trabalhoApi

spring.datasource.url=jdbc:postgresql://localhost:5432/SerratecFlix
spring.datasource.username=postgres
spring.datasource.password=12345
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

tmdb.api.token=eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiIwNzMyZWM3OWEzMDYxZGQyYTdjNTIxM2JhYzU1MzJmYyIsIm5iZiI6MTc3OTgyNDY1Ny4zMzMsInN1YiI6IjZhMTVmODExNDA4NTBjM2I4ZjkwZWMzMSIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.k5J6k7QRbn_ZqhQYSIUpSj_J5g1qpfg1eL30fUJdiYk
jwt.secret=sua-chave-secreta-muito-longa-e-segura-aqui-32chars
jwt.expiration=86400000

omdb.api.key= f7c17150